/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
MARK REUBEN E. FORTUITO - DOCUMENT SPECIALIST
JOSHUA P. GAGARIN - BUSINESS ANALYST
LEI AIREL A. LOQUIS - SYSTEM ANALYST
JOHN CHRISTOFER LUCERO - ASSISTANT PROGRAMMER
JEREMY L. MALANA - LEAD PROGRAMMER
MIGUEL ROSE N. SORIANO - PROJECT MANAGER
*/
package Authenticate;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Jeremy Malana
 */
public class ForgotPasswordPageForm extends javax.swing.JFrame {



    /**
     * Creates new form ForgotPasswordForm
     */
    public ForgotPasswordPageForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jPasswordField1_new_password.setEnabled(false);
        jPasswordField2_confirm_password.setEnabled(false);
        jButton3_reset.setEnabled(false);
        
        jCheckBox1_ShowPassword.addActionListener(this::jCheckBox1_ShowPasswordActionPerformed);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_email = new javax.swing.JTextField();
        jButton1_send = new javax.swing.JButton();
        jTextField2_code = new javax.swing.JTextField();
        jButton2_verify_code = new javax.swing.JButton();
        jPasswordField1_new_password = new javax.swing.JPasswordField();
        jPasswordField2_confirm_password = new javax.swing.JPasswordField();
        jButton3_reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox1_ShowPassword = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 215, 215));
        jPanel1.setForeground(new java.awt.Color(255, 251, 244));

        jPanel2.setBackground(new java.awt.Color(245, 232, 182));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 18, 13));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("<html><body style=\"text-align:center;\">Forgot<br>Password</body></html>");

        jTextField1_email.setBackground(new java.awt.Color(245, 232, 182));
        jTextField1_email.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jTextField1_email.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1_email.setText("Email");
        jTextField1_email.setBorder(null);
        jTextField1_email.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField1_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_emailFocusLost(evt);
            }
        });
        jTextField1_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_emailActionPerformed(evt);
            }
        });

        jButton1_send.setBackground(new java.awt.Color(233, 190, 95));
        jButton1_send.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton1_send.setForeground(new java.awt.Color(17, 18, 13));
        jButton1_send.setText("SEND");
        jButton1_send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_sendActionPerformed(evt);
            }
        });

        jTextField2_code.setBackground(new java.awt.Color(245, 232, 182));
        jTextField2_code.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jTextField2_code.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2_code.setText("Verification Code");
        jTextField2_code.setBorder(null);
        jTextField2_code.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField2_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2_codeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2_codeFocusLost(evt);
            }
        });
        jTextField2_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_codeActionPerformed(evt);
            }
        });

        jButton2_verify_code.setBackground(new java.awt.Color(233, 190, 95));
        jButton2_verify_code.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton2_verify_code.setForeground(new java.awt.Color(17, 18, 13));
        jButton2_verify_code.setText("VERIFY CODE");
        jButton2_verify_code.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_verify_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_verify_codeActionPerformed(evt);
            }
        });

        jPasswordField1_new_password.setBackground(new java.awt.Color(245, 232, 182));
        jPasswordField1_new_password.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jPasswordField1_new_password.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1_new_password.setText("New Password");
        jPasswordField1_new_password.setToolTipText("");
        jPasswordField1_new_password.setBorder(null);
        jPasswordField1_new_password.setCaretColor(new java.awt.Color(0, 0, 0));
        jPasswordField1_new_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1_new_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1_new_passwordFocusLost(evt);
            }
        });
        jPasswordField1_new_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_new_passwordActionPerformed(evt);
            }
        });

        jPasswordField2_confirm_password.setBackground(new java.awt.Color(245, 232, 182));
        jPasswordField2_confirm_password.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jPasswordField2_confirm_password.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField2_confirm_password.setText("Confirm Password");
        jPasswordField2_confirm_password.setBorder(null);
        jPasswordField2_confirm_password.setCaretColor(new java.awt.Color(0, 0, 0));
        jPasswordField2_confirm_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2_confirm_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2_confirm_passwordFocusLost(evt);
            }
        });
        jPasswordField2_confirm_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2_confirm_passwordActionPerformed(evt);
            }
        });

        jButton3_reset.setBackground(new java.awt.Color(233, 190, 95));
        jButton3_reset.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jButton3_reset.setForeground(new java.awt.Color(17, 18, 13));
        jButton3_reset.setText("RESET");
        jButton3_reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_resetActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(233, 190, 95));
        jButton1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(30, 30, 30));
        jButton1.setText("BACK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jCheckBox1_ShowPassword.setBackground(new java.awt.Color(245, 232, 182));
        jCheckBox1_ShowPassword.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jCheckBox1_ShowPassword.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1_ShowPassword.setText("Show Password");
        jCheckBox1_ShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_ShowPasswordActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/otp.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/password.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/password.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2_verify_code, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2_code, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1_send, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(420, 420, 420)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBox1_ShowPassword)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1_email))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPasswordField2_confirm_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPasswordField1_new_password, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_email, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1_send, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2_code, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButton2_verify_code, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1_new_password, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField2_confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1_ShowPassword)
                .addGap(18, 18, 18)
                .addComponent(jButton3_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_emailActionPerformed

    private void jButton1_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_sendActionPerformed
        // TODO add your handling code here:
        String email = jTextField1_email.getText();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Main_Authenticate.sendResetCodeEmail(email);
        }
    }//GEN-LAST:event_jButton1_sendActionPerformed

    private void jTextField2_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_codeActionPerformed

    private void jButton2_verify_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_verify_codeActionPerformed
        // TODO add your handling code here:
        String email = jTextField1_email.getText();
        String resetCode = jTextField2_code.getText();
        if (email.isEmpty() || resetCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email and reset code", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Main_Authenticate.verifyResetCode(email, resetCode)) {
            JOptionPane.showMessageDialog(this, "Reset code verified. You can now reset your password.", "Success", JOptionPane.INFORMATION_MESSAGE);
            jPasswordField1_new_password.setEnabled(true);
            jPasswordField2_confirm_password.setEnabled(true);
            jButton3_reset.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid or expired reset code", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2_verify_codeActionPerformed

    private void jPasswordField1_new_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_new_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_new_passwordActionPerformed

    private void jPasswordField2_confirm_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2_confirm_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2_confirm_passwordActionPerformed

    private void jButton3_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_resetActionPerformed
        // TODO add your handling code here:
        String email = jTextField1_email.getText();
        String newPassword = new String(jPasswordField1_new_password.getPassword());
        String confirmPassword = new String(jPasswordField2_confirm_password.getPassword());

        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter and confirm your new password", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Main_Authenticate.resetPassword(email, newPassword);
        } 
    }//GEN-LAST:event_jButton3_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginPageForm login = new LoginPageForm();
        login.show();
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_emailFocusGained
        // TODO add your handling code here:
        if(jTextField1_email.getText().equals("Email")) {
            jTextField1_email.setText("");
        }
    }//GEN-LAST:event_jTextField1_emailFocusGained

    private void jTextField1_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_emailFocusLost
        // TODO add your handling code here:
        if(jTextField1_email.getText().isEmpty()) {
            jTextField1_email.setText("Email");
        }
    }//GEN-LAST:event_jTextField1_emailFocusLost

    private void jTextField2_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2_codeFocusGained
        // TODO add your handling code here:
        if(jTextField2_code.getText().equals("Verification Code")) {
            jTextField2_code.setText("");
        }
    }//GEN-LAST:event_jTextField2_codeFocusGained

    private void jTextField2_codeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2_codeFocusLost
        // TODO add your handling code here:
        if(jTextField2_code.getText().isEmpty()) {
            jTextField2_code.setText("Verification Code");
        }
    }//GEN-LAST:event_jTextField2_codeFocusLost

    private void jPasswordField1_new_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_new_passwordFocusGained
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField1_new_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.equals("New Password")) {
            jPasswordField1_new_password.setText("");
            jPasswordField1_new_password.setEchoChar('•');
        }
    }//GEN-LAST:event_jPasswordField1_new_passwordFocusGained

    private void jPasswordField1_new_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_new_passwordFocusLost
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField1_new_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.isEmpty()) {
            jPasswordField1_new_password.setEchoChar((char)0);
            jPasswordField1_new_password.setText("New Password");
        }
    }//GEN-LAST:event_jPasswordField1_new_passwordFocusLost

    private void jPasswordField2_confirm_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2_confirm_passwordFocusGained
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField2_confirm_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.equals("Confirm Password")) {
            jPasswordField2_confirm_password.setText("");
            jPasswordField2_confirm_password.setEchoChar('•');
        }
    }//GEN-LAST:event_jPasswordField2_confirm_passwordFocusGained

    private void jPasswordField2_confirm_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2_confirm_passwordFocusLost
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField2_confirm_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.isEmpty()) {
            jPasswordField2_confirm_password.setEchoChar((char)0);
            jPasswordField2_confirm_password.setText("Confirm Password");
        }
    }//GEN-LAST:event_jPasswordField2_confirm_passwordFocusLost

    private void jCheckBox1_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_ShowPasswordActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1_ShowPassword.isSelected()) {
            jPasswordField1_new_password.setEchoChar((char) 0);
            jPasswordField2_confirm_password.setEchoChar((char) 0);
        } else {
            jPasswordField1_new_password.setEchoChar('•');
            jPasswordField2_confirm_password.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox1_ShowPasswordActionPerformed


    // Method to enable password fields
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordPageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_send;
    private javax.swing.JButton jButton2_verify_code;
    private javax.swing.JButton jButton3_reset;
    private javax.swing.JCheckBox jCheckBox1_ShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1_new_password;
    private javax.swing.JPasswordField jPasswordField2_confirm_password;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1_email;
    private javax.swing.JTextField jTextField2_code;
    // End of variables declaration//GEN-END:variables
}
