/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
MARK REUBEN E. FORTUITO - DOCUMENT SPECIALIST
JOSHUA P. GAGARIN - BUSINESS ANALYST
LEI AIREL A. LOQUIS - SYSTEM ANALYST
JOHN CHRISTOFER LUCERO - ASSISTANT PROGRAMMER
JEREMY L. MALANA - LEAD PROGRAMMER
MIGUEL ROSE N. SORIANO - PROJECT MANAGER
*/
package Authenticate;

import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author Jeremy Malana
 */
public class RegistrationPageForm extends javax.swing.JFrame {
       
    /**
     * Creates new form RegistrationPage
     */
    public RegistrationPageForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        jPasswordField1_password.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String password = new String(jPasswordField1_password.getPassword());
                Main_Authenticate.evaluatePasswordStrength(password, RegistrationPageForm.this);
            }
        });

        jPasswordField2_confirm_password.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String password = new String(jPasswordField1_password.getPassword());
                Main_Authenticate.evaluatePasswordStrength(password, RegistrationPageForm.this);
            }
        });

        jCheckBox3_showPassword.addActionListener(this::jCheckBox3_showPasswordActionPerformed);

        jCheckBox1_Terms.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (jCheckBox1_Terms.isSelected() && !Main_Authenticate.isTermsShown()) {
                    Main_Authenticate.showTermsAndConditions(RegistrationPageForm.this);
                    Main_Authenticate.setTermsShown(true);
                }
            }
        });
    }

    public String getName() {
        return jTextField1_name.getText();
    }

    // Method to get the email input
    public String getEmail() {
        return jTextField2_email.getText();
    }

    // Method to get the username input
    public String getUsername() {
        return jTextField3_username.getText();
    }

    // Method to get the password input
    public String getPassword() {
        return new String(jPasswordField1_password.getPassword());
    }

    // Method to get the confirm password input
    public String getConfirmPassword() {
        return new String(jPasswordField2_confirm_password.getPassword());
    }

    // Method to check if terms are selected
    public boolean isTermsSelected() {
        return jCheckBox1_Terms.isSelected();
    }

    // Method to set the progress bar value
    public void setProgressBarValue(int value) {
        jProgressBar1_pw_eval.setValue(value);
    }

    // Method to set the progress bar color
    public void setProgressBarColor(Color color) {
        jProgressBar1_pw_eval.setForeground(color);
    }

    // Method to set the password strength label
    public void setPasswordStrengthLabel(String text) {
        jLabel10_pw_strength.setText(text);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1_name = new javax.swing.JTextField();
        jTextField2_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3_username = new javax.swing.JTextField();
        jPasswordField1_password = new javax.swing.JPasswordField();
        jProgressBar1_pw_eval = new javax.swing.JProgressBar();
        jLabel10_pw_strength = new javax.swing.JLabel();
        jPasswordField2_confirm_password = new javax.swing.JPasswordField();
        jCheckBox3_showPassword = new javax.swing.JCheckBox();
        jButton2_signup = new javax.swing.JButton();
        jCheckBox1_Terms = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1_login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 215, 215));

        jPanel2.setBackground(new java.awt.Color(245, 232, 182));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jTextField1_name.setBackground(new java.awt.Color(245, 232, 182));
        jTextField1_name.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jTextField1_name.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1_name.setText("Name");
        jTextField1_name.setBorder(null);
        jTextField1_name.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField1_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_nameFocusLost(evt);
            }
        });

        jTextField2_email.setBackground(new java.awt.Color(245, 232, 182));
        jTextField2_email.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jTextField2_email.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2_email.setText("Email");
        jTextField2_email.setBorder(null);
        jTextField2_email.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField2_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2_emailFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 18, 11));
        jLabel3.setText("Create Account");

        jTextField3_username.setBackground(new java.awt.Color(245, 232, 182));
        jTextField3_username.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jTextField3_username.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3_username.setText("Username");
        jTextField3_username.setBorder(null);
        jTextField3_username.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField3_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3_usernameFocusLost(evt);
            }
        });
        jTextField3_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_usernameActionPerformed(evt);
            }
        });

        jPasswordField1_password.setBackground(new java.awt.Color(245, 232, 182));
        jPasswordField1_password.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jPasswordField1_password.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1_password.setText("Password");
        jPasswordField1_password.setBorder(null);
        jPasswordField1_password.setCaretColor(new java.awt.Color(0, 0, 0));
        jPasswordField1_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1_passwordFocusLost(evt);
            }
        });

        jProgressBar1_pw_eval.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jProgressBar1_pw_eval.setForeground(new java.awt.Color(37, 35, 33));
        jProgressBar1_pw_eval.setPreferredSize(new java.awt.Dimension(146, 10));

        jLabel10_pw_strength.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel10_pw_strength.setForeground(new java.awt.Color(37, 35, 33));

        jPasswordField2_confirm_password.setBackground(new java.awt.Color(245, 232, 182));
        jPasswordField2_confirm_password.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jPasswordField2_confirm_password.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField2_confirm_password.setText("Confirm Password");
        jPasswordField2_confirm_password.setBorder(null);
        jPasswordField2_confirm_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2_confirm_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2_confirm_passwordFocusLost(evt);
            }
        });

        jCheckBox3_showPassword.setBackground(new java.awt.Color(245, 232, 182));
        jCheckBox3_showPassword.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jCheckBox3_showPassword.setForeground(new java.awt.Color(37, 35, 33));
        jCheckBox3_showPassword.setText("Show Password");
        jCheckBox3_showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3_showPasswordActionPerformed(evt);
            }
        });

        jButton2_signup.setBackground(new java.awt.Color(233, 190, 95));
        jButton2_signup.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jButton2_signup.setForeground(new java.awt.Color(37, 35, 33));
        jButton2_signup.setText("SIGN UP");
        jButton2_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_signupActionPerformed(evt);
            }
        });

        jCheckBox1_Terms.setBackground(new java.awt.Color(245, 232, 182));
        jCheckBox1_Terms.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jCheckBox1_Terms.setForeground(new java.awt.Color(37, 35, 33));
        jCheckBox1_Terms.setText("<html>I Agree to the <a href='#'>Terms & Conditions</a></html>");
        jCheckBox1_Terms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_TermsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 35, 33));
        jLabel9.setText("Already have an account?");
        jLabel9.setToolTipText("");

        jButton1_login.setBackground(new java.awt.Color(233, 190, 95));
        jButton1_login.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jButton1_login.setForeground(new java.awt.Color(37, 35, 33));
        jButton1_login.setText("LOGIN");
        jButton1_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_loginActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(30, 30, 30));

        jSeparator2.setForeground(new java.awt.Color(30, 30, 30));

        jSeparator3.setForeground(new java.awt.Color(30, 30, 30));

        jSeparator4.setForeground(new java.awt.Color(30, 30, 30));

        jSeparator5.setForeground(new java.awt.Color(30, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/fullname.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/username.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/password.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/password.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jProgressBar1_pw_eval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10_pw_strength, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)
                            .addComponent(jTextField2_email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox3_showPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1_name)
                                    .addComponent(jButton2_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3)
                            .addComponent(jPasswordField1_password)
                            .addComponent(jSeparator4)
                            .addComponent(jPasswordField2_confirm_password)
                            .addComponent(jSeparator5)
                            .addComponent(jTextField3_username)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jCheckBox1_Terms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(199, 199, 199))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1_name, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2_email, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3_username, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1_password, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1_pw_eval, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10_pw_strength, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField2_confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3_showPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1_Terms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_usernameActionPerformed

    private void jCheckBox1_TermsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_TermsActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1_Terms.isSelected()) {
            Main_Authenticate.showTermsAndConditions(this);
        }
    }//GEN-LAST:event_jCheckBox1_TermsActionPerformed

    private void jButton1_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_loginActionPerformed
        // TODO add your handling code here:
        LoginPageForm login = new LoginPageForm();
        login.show();
        
        this.dispose();
    }//GEN-LAST:event_jButton1_loginActionPerformed

    private void jButton2_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_signupActionPerformed
        // TODO add your handling code here:
        Main_Authenticate.handleRegistration(this);
    }//GEN-LAST:event_jButton2_signupActionPerformed

    private void jCheckBox3_showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3_showPasswordActionPerformed
        // TODO add your handling code here:
        if (jCheckBox3_showPassword.isSelected()) {
            jPasswordField1_password.setEchoChar((char) 0);
            jPasswordField2_confirm_password.setEchoChar((char) 0);
        } else {
            jPasswordField1_password.setEchoChar('•');
            jPasswordField2_confirm_password.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox3_showPasswordActionPerformed

    private void jTextField1_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_nameFocusGained
        // TODO add your handling code here:
        if(jTextField1_name.getText().equals("Name")) {
            jTextField1_name.setText("");
        }
    }//GEN-LAST:event_jTextField1_nameFocusGained

    private void jTextField1_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_nameFocusLost
        // TODO add your handling code here:
        if(jTextField1_name.getText().isEmpty()) {
            jTextField1_name.setText("Name");
        }
    }//GEN-LAST:event_jTextField1_nameFocusLost

    private void jTextField2_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2_emailFocusGained
        // TODO add your handling code here:
        if(jTextField2_email.getText().equals("Email")) {
            jTextField2_email.setText("");
        }
    }//GEN-LAST:event_jTextField2_emailFocusGained

    private void jTextField2_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2_emailFocusLost
        // TODO add your handling code here:
        if(jTextField2_email.getText().isEmpty()) {
            jTextField2_email.setText("Email");
        }
    }//GEN-LAST:event_jTextField2_emailFocusLost

    private void jTextField3_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3_usernameFocusGained
        // TODO add your handling code here:
        if(jTextField3_username.getText().equals("Username")) {
            jTextField3_username.setText("");
        }
    }//GEN-LAST:event_jTextField3_usernameFocusGained

    private void jTextField3_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3_usernameFocusLost
        // TODO add your handling code here:
        if(jTextField3_username.getText().isEmpty()) {
            jTextField3_username.setText("Username");
        }
    }//GEN-LAST:event_jTextField3_usernameFocusLost

    private void jPasswordField1_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_passwordFocusGained
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField1_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.equals("Password")) {
            jPasswordField1_password.setText("");
            jPasswordField1_password.setEchoChar('•');
        }
    }//GEN-LAST:event_jPasswordField1_passwordFocusGained

    private void jPasswordField1_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_passwordFocusLost
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField1_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.isEmpty()) {
            jPasswordField1_password.setEchoChar((char)0);
            jPasswordField1_password.setText("Password");
        }
    }//GEN-LAST:event_jPasswordField1_passwordFocusLost

    private void jPasswordField2_confirm_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2_confirm_passwordFocusGained
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField2_confirm_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.equals("Confirm Password")) {
            jPasswordField2_confirm_password.setText("");
            jPasswordField2_confirm_password.setEchoChar('•');
        }
    }//GEN-LAST:event_jPasswordField2_confirm_passwordFocusGained

    private void jPasswordField2_confirm_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2_confirm_passwordFocusLost
        // TODO add your handling code here:
        char[] passwordChars = jPasswordField2_confirm_password.getPassword();
        String passwordText = new String(passwordChars);
        
        if(passwordText.isEmpty()) {
            jPasswordField2_confirm_password.setEchoChar((char)0);
            jPasswordField2_confirm_password.setText("Confirm Password");
        }
    }//GEN-LAST:event_jPasswordField2_confirm_passwordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationPageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_login;
    private javax.swing.JButton jButton2_signup;
    private javax.swing.JCheckBox jCheckBox1_Terms;
    private javax.swing.JCheckBox jCheckBox3_showPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10_pw_strength;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1_password;
    private javax.swing.JPasswordField jPasswordField2_confirm_password;
    private javax.swing.JProgressBar jProgressBar1_pw_eval;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1_name;
    private javax.swing.JTextField jTextField2_email;
    private javax.swing.JTextField jTextField3_username;
    // End of variables declaration//GEN-END:variables
}
