/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
MARK REUBEN E. FORTUITO - DOCUMENT SPECIALIST
JOSHUA P. GAGARIN - BUSINESS ANALYST
LEI AIREL A. LOQUIS - SYSTEM ANALYST
JOHN CHRISTOFER LUCERO - ASSISTANT PROGRAMMER
JEREMY L. MALANA - LEAD PROGRAMMER
MIGUEL ROSE N. SORIANO - PROJECT MANAGER
*/
package Customer;

/**
 *
 * @author Jeremy Malana
 */
public class ChatBotPageForm extends javax.swing.JFrame {
    private ChatBot chatBot;
    /**
     * Creates new form ChatBotPageForm
     */
    public ChatBotPageForm() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        chatBot = new ChatBot();
        chatBot.displayWelcomeMessage(jTextArea_DisplayMessage);
        jTextArea_DisplayMessage.setLineWrap(true);
        jTextArea_DisplayMessage.setWrapStyleWord(true);
        jTextArea_DisplayMessage.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_DisplayMessage = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Q1 = new javax.swing.JLabel();
        jLabel_Q2 = new javax.swing.JLabel();
        jLabel_Q3 = new javax.swing.JLabel();
        jLabel_Q4 = new javax.swing.JLabel();
        jLabel_Q5 = new javax.swing.JLabel();
        jLabel_Q6 = new javax.swing.JLabel();
        jLabel_Q7 = new javax.swing.JLabel();
        jLabel_Q8 = new javax.swing.JLabel();
        jButton1_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(215, 215, 215));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));
        jPanel1.setToolTipText("");

        jTextArea_DisplayMessage.setBackground(new java.awt.Color(244, 248, 255));
        jTextArea_DisplayMessage.setColumns(20);
        jTextArea_DisplayMessage.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jTextArea_DisplayMessage.setForeground(new java.awt.Color(30, 30, 30));
        jTextArea_DisplayMessage.setRows(5);
        jTextArea_DisplayMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jTextArea_DisplayMessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(28, 28, 28));

        jLabel_Q1.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q1.setText("What are the store hours?");
        jLabel_Q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q1MouseClicked(evt);
            }
        });

        jLabel_Q2.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q2.setText("How can I place an order?");
        jLabel_Q2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q2MouseClicked(evt);
            }
        });

        jLabel_Q3.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q3.setText("Can I order without registering?");
        jLabel_Q3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q3MouseClicked(evt);
            }
        });

        jLabel_Q4.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q4.setText("How do I track my order? ");
        jLabel_Q4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q4MouseClicked(evt);
            }
        });

        jLabel_Q5.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q5.setText("What payment methods are accepted?");
        jLabel_Q5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q5MouseClicked(evt);
            }
        });

        jLabel_Q6.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q6.setText("How can I modify or cancel my order? ");
        jLabel_Q6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q6MouseClicked(evt);
            }
        });

        jLabel_Q7.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q7.setText("Is delivery available?");
        jLabel_Q7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q7MouseClicked(evt);
            }
        });

        jLabel_Q8.setFont(new java.awt.Font("Montserrat", 1, 32)); // NOI18N
        jLabel_Q8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Q8.setText("How do I contact the store for further inquiries?");
        jLabel_Q8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Q8MouseClicked(evt);
            }
        });

        jButton1_Back.setBackground(new java.awt.Color(233, 190, 95));
        jButton1_Back.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton1_Back.setForeground(new java.awt.Color(0, 0, 0));
        jButton1_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jButton1_Back.setText("BACK");
        jButton1_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Q8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Q1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q2)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q4)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q5)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q6)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q7)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Q8)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1_BackActionPerformed

    private void jLabel_Q1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q1MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(1, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q1MouseClicked

    private void jLabel_Q2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q2MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(2, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q2MouseClicked

    private void jLabel_Q3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q3MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(3, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q3MouseClicked

    private void jLabel_Q4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q4MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(4, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q4MouseClicked

    private void jLabel_Q5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q5MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(5, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q5MouseClicked

    private void jLabel_Q6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q6MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(6, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q6MouseClicked

    private void jLabel_Q7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q7MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(7, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q7MouseClicked

    private void jLabel_Q8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Q8MouseClicked
        // TODO add your handling code here:
        chatBot.displayAnswer(8, jTextArea_DisplayMessage);
    }//GEN-LAST:event_jLabel_Q8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatBotPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatBotPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatBotPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatBotPageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatBotPageForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Back;
    private javax.swing.JLabel jLabel_Q1;
    private javax.swing.JLabel jLabel_Q2;
    private javax.swing.JLabel jLabel_Q3;
    private javax.swing.JLabel jLabel_Q4;
    private javax.swing.JLabel jLabel_Q5;
    private javax.swing.JLabel jLabel_Q6;
    private javax.swing.JLabel jLabel_Q7;
    private javax.swing.JLabel jLabel_Q8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_DisplayMessage;
    // End of variables declaration//GEN-END:variables
}
